#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Run from the stretch_ai repo root regardless of where this is invoked.
cd "$(dirname "${BASH_SOURCE[0]}")/.."
REPO_ROOT="$PWD"

# stretch_ai doesn't read a .env; keep captured values outside the repo.
mkdir -p "$HOME/.stretch"
ENV_FILE="$HOME/.stretch/dynamem.env"

# Workstation containers. conda lives inside these images, not on the host.
BASE_IMAGE="hellorobotinc/stretch-ai_cuda-11.8:latest"
LOCAL_IMAGE="stretch-ai-dynamem:local"   # BASE_IMAGE + current deps, av removed, SAM2 installed
IMAGE_PY="/root/miniforge3/envs/stretch_ai/bin/python"

# ok "msg" prints a green check line.
ok() { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }

# verify_local_image: GPU visible, SAM2 importable, av absent (av deadlocks OpenCV windows).
verify_local_image() {
  docker run --rm --gpus all -v "$REPO_ROOT:/app" "$LOCAL_IMAGE" "$IMAGE_PY" -c '
import sys, importlib.util as u, torch
checks = {"torch sees GPU": torch.cuda.is_available(), "sam2 installed": u.find_spec("sam2") is not None, "av removed": u.find_spec("av") is None}
for k, v in checks.items(): print("   ", "ok " if v else "BAD", k)
sys.exit(0 if all(checks.values()) else 1)' 2>/dev/null
}

# build_local_image: pull the base image, install this checkout's deps, remove av, add SAM2, commit.
build_local_image() {
  docker image inspect "$BASE_IMAGE" >/dev/null 2>&1 || docker pull "$BASE_IMAGE" || return 1
  docker rm -f stretch_deps >/dev/null 2>&1 || true
  if ! docker run --name stretch_deps --gpus all -v "$REPO_ROOT:/app" "$BASE_IMAGE" bash -c '
      set -e
      P=/root/miniforge3/envs/stretch_ai/bin
      $P/pip install -e /app/src
      $P/pip uninstall -y av
      SAM2_BUILD_CUDA=0 $P/pip install -e /app/third_party/segment-anything-2'; then
    docker rm -f stretch_deps >/dev/null 2>&1 || true
    return 1
  fi
  # Reset CMD, otherwise the image would re-run the install script on every start.
  docker commit --change 'CMD ["/bin/bash"]' stretch_deps "$LOCAL_IMAGE" >/dev/null
  docker rm stretch_deps >/dev/null
}

banner "DynaMem setup · Docker on robot + workstation · visual servo"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Workstation: GPU + Docker"
say "The workstation container needs the NVIDIA driver, Docker without sudo, and"
say "the NVIDIA container runtime."
problems=0
if nvidia-smi >/dev/null 2>&1; then
  ok "GPU: $(nvidia-smi --query-gpu=name,driver_version --format=csv,noheader)"
else
  warn "nvidia-smi fails. If it's a driver/library mismatch, reboot and re-run."; problems=1
fi
if docker info >/dev/null 2>&1; then
  ok "docker runs without sudo"
else
  warn "docker needs sudo or isn't running. Fix: sudo usermod -aG docker \$USER, then log out and back in"; problems=1
fi
if docker info 2>/dev/null | grep -qi "runtimes:.*nvidia"; then
  ok "NVIDIA container runtime registered"
else
  warn "NVIDIA container runtime missing. Fix: bash scripts/install_nvidia_container_toolkit.sh"; problems=1
fi
if (( problems )); then
  note "Fix the items above, then re-run: bash learning/setup_dynamem.sh"
  exit 1
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Workstation: build the local DynaMem image"
say "The published image ($BASE_IMAGE) predates this checkout, ships PyAV"
say "(which freezes OpenCV windows) and lacks SAM2. We build $LOCAL_IMAGE on"
say "top of it once, so containers start ready to run."
build=false
if docker image inspect "$LOCAL_IMAGE" >/dev/null 2>&1; then
  ok "$LOCAL_IMAGE exists"
  say "Verifying it…"
  if verify_local_image; then
    note "Rebuild only after a git pull that changes src/setup.py."
    confirm "Rebuild it anyway?" && build=true
  else
    warn "$LOCAL_IMAGE failed verification."
    confirm "Rebuild it now?" && build=true
  fi
elif confirm "Build it now? (pulls ~7 GB if needed, then pip installs; several minutes)"; then
  build=true
else
  SKIPPED+=("build $LOCAL_IMAGE (re-run this wizard)")
fi
if $build; then
  if build_local_image; then
    ok "built $LOCAL_IMAGE"
    verify_local_image || SKIPPED+=("$LOCAL_IMAGE built but failed verification")
  else
    warn "build failed; scroll up for the error, fix it, and re-run."
    exit 1
  fi
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Robot: one-time Docker + repo prep"
say "Do this in a terminal ON THE ROBOT (ssh hello-robot@<robot>). Skip what's already done."
note "Unplug the robot's USB dongle before using Docker (per the stretch_ai docs)."
printf '\n'
step "Install Docker:        sudo apt-get update && sudo apt-get install docker.io"
step "Run it without sudo:   sudo usermod -aG docker \$USER && newgrp docker"
step "Verify:                docker run hello-world   → prints 'Hello from Docker!'"
step "Clone the repo:        git clone https://github.com/hello-robot/stretch_ai.git"
pause "Press Enter once Docker works and stretch_ai is cloned on the robot"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Robot: power on and home"
say "Clear the space around the robot: homing moves the lift, arm and gripper."
step "Turn the robot on and wait for it to boot."
step "On the robot, run:  stretch_free_robot_process.py"
step "Then run:           stretch_robot_home.py"
note "Needed once per power-on. Already homed? Skip."
pause "Press Enter once homing finishes"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Network: robot IP"
say "The workstation talks to the robot over ZMQ on ports 4401-4404."
step "Prefer the robot's hostname (e.g. stretch-re2-2060.uconnect.utah.edu): a DHCP IP can change after a reboot."
step "No hostname? On the robot, run:  hostname -I   (take the address on the same network as this workstation)"
ask ROBOT_IP "Robot hostname or IP address:"
until [[ "$ROBOT_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || getent hosts "$ROBOT_IP" >/dev/null; do
  warn "That isn't an IPv4 address (x.x.x.x) or a hostname this workstation can resolve."
  ask ROBOT_IP "Robot hostname or IP address:"
done
write_env ROBOT_IP "$ROBOT_IP"
[[ -z "$(_existing ROBOT_USER || true)" ]] && note "Default SSH user on Stretch is hello-robot."
ask ROBOT_USER "Robot SSH user (e.g. hello-robot):"
[[ -z "$ROBOT_USER" ]] && ROBOT_USER="hello-robot"
write_env ROBOT_USER "$ROBOT_USER"
if ping -c 2 -W 2 "$ROBOT_IP" >/dev/null 2>&1; then
  ok "robot answers ping"
else
  warn "no ping reply from $ROBOT_IP: check both machines are on the same network."
  pause "Press Enter to continue anyway"
fi
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Robot: launch the ROS2 bridge server"
say "In a terminal ON THE ROBOT:"
step "docker ps   → if a stretch-ai-ros2-bridge container is already Up, use it (or docker stop <id>)"
step "cd <stretch_ai clone> && ./scripts/run_stretch_ai_ros2_bridge_server.sh   (leave it running)"
note "First time on this robot? Add --update to pull the image (~18 GB)."
say ""
say "It's up when the robot beeps twice, the lidar spins, and the log shows"
say "'Starting to send full state'."
pause "Press Enter once the server is running"
while true; do
  closed=()
  for port in 4401 4402 4403 4404; do
    timeout 2 bash -c "</dev/tcp/$ROBOT_IP/$port" 2>/dev/null || closed+=("$port")
  done
  if (( ${#closed[@]} == 0 )); then ok "ports 4401-4404 reachable on $ROBOT_IP"; break; fi
  warn "can't reach port(s) ${closed[*]} on $ROBOT_IP (server still starting, or a firewall)."
  confirm "Check again?" || { SKIPPED+=("robot ports ${closed[*]} unreachable"); break; }
done
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "URDF: copy the calibrated URDF from the robot"
say "Placing uses your robot's calibrated URDF; dynamem_urdf.py then adds the fake"
say "base joint DynaMem's manipulation expects. The container sees it via the /app mount."
URDF_LOCAL="src/stretch/config/urdf/stretch.urdf"
URDF_REMOTE="ament_ws/src/stretch_ros2/stretch_description/urdf/stretch.urdf"
copy_urdf=true
if [[ -f "$URDF_LOCAL.stock" ]] && grep -q 'name="joint_fake"' "$URDF_LOCAL"; then
  ok "already copied and patched (stock backup present, joint_fake found)"
  note "Re-copy only if you recalibrated the robot."
  confirm "Copy it again?" || copy_urdf=false
fi
if $copy_urdf; then
  note "from: $ROBOT_USER@$ROBOT_IP:~/$URDF_REMOTE"
  note "to:   $URDF_LOCAL  (the stock copy is backed up to stretch.urdf.stock)"
  if confirm "Copy it now? (scp may ask for the robot password)"; then
    [[ -f "$URDF_LOCAL.stock" ]] || cp "$URDF_LOCAL" "$URDF_LOCAL.stock"
    if scp "$ROBOT_USER@$ROBOT_IP:$URDF_REMOTE" "$URDF_LOCAL"; then
      ok "copied"
      # dynamem_urdf.py only needs the standard library, so host python3 is enough.
      if python3 src/stretch/config/dynamem_urdf.py --urdf-path "$URDF_LOCAL"; then
        ok "patched with dynamem_urdf.py (joint_fake added)"
      else
        SKIPPED+=("python3 src/stretch/config/dynamem_urdf.py --urdf-path $URDF_LOCAL")
      fi
    else
      warn "scp failed; check the user/IP and that the file exists on the robot."
      SKIPPED+=("copy calibrated URDF from robot, then run dynamem_urdf.py")
    fi
  else
    SKIPPED+=("copy calibrated URDF from robot, then run dynamem_urdf.py")
  fi
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Workstation: start the DynaMem container"
say "The container needs an X display to show camera windows, so start it from a"
say "terminal connected with X forwarding (uppercase -Y; lowercase -x disables it)."
say ""
say "From your laptop, open a SECOND terminal:"
step "ssh -Y -L 9090:localhost:9090 -L 9877:localhost:9877 $USER@<this workstation>"
note "The -L ports let your laptop's browser open rerun's web viewer (localhost:9090)."
step "echo \$DISPLAY   → must print e.g. localhost:10.0"
step "$REPO_ROOT/learning/run_dynamem_container.sh"
say ""
say "You land in (stretch_ai) root@…:/app#. No pip install needed."
note "Reconnected over SSH? Exit and restart the container: display and cookie change per login."
pause "Press Enter once you're at the container prompt"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Smoke test: view_images (inside the container)"
say "This proves the container ↔ robot link end to end."
warn "The robot's gripper will open and its arm will move: keep the area clear."
say "In the container terminal, run:"
step "python -m stretch.app.view_images --robot_ip $ROBOT_IP"
say "Camera windows appear on your laptop. Click one and press q to quit."
note "No windows and no error after the image shapes print? PyAV is back: pip uninstall -y av"
pause "Press Enter once you've seen the camera feed"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "First DynaMem run (inside the container)"
DYNAMEM_CMD="python -m stretch.app.run_dynamem --robot_ip $ROBOT_IP --visual-servo"
say "Before starting:"
note "  • a robot's width of clear space on every side: it spins 360° in place first"
note "  • clear low objects: anything under 20 cm tall is not seen as an obstacle"
note "  • keep people out of the path: it doesn't react to things moving in front of it"
note "  • runstop within reach"
say ""
say "Stuck in a tight spot? Drive out first (click the Robot View window; w/s/a/d; q to quit):"
step "python -m stretch.app.keyboard_teleop --robot_ip $ROBOT_IP"
say "Then run:"
step "$DYNAMEM_CMD"
note "Mode prompt: E = explore & map, M = pick & place (asks object, then receptacle)."
note "It asks before each navigate/pick/place step; add -S only once you trust it."
say ""
warn "If it misbehaves: press the runstop, then Ctrl-C DynaMem BEFORE releasing the runstop."
pause "Press Enter when you're done"

finish
say "Next time, follow the runbook: learning/dynamem_runbook.md"
say "  robot:       home, then ./scripts/run_stretch_ai_ros2_bridge_server.sh"
say "  workstation: learning/run_dynamem_container.sh  →  $DYNAMEM_CMD"
printf '\n'
